// <auto-generated />
using DevPortfolioServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevPortfolioServer.Migrations
{
    [DbContext(typeof(AppDataDBContext))]
    [Migration("20230706182523_MyFirstMigration")]
    partial class MyFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("DevPortfolioShared.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailImagePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "A description of a Category 1",
                            Name = "Category 1",
                            ThumbnailImagePath = "uploads/plaseholder.jpg"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "A description of a Category 2",
                            Name = "Category 2",
                            ThumbnailImagePath = "uploads/plaseholder.jpg"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "A description of a Category 3",
                            Name = "Category 3",
                            ThumbnailImagePath = "uploads/plaseholder.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
